name: Docker Image CI

on:
  push:
    branches: [ "d-b" ]
  pull_request:
    branches: [ "d-b" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd frontend/micro-ui && docker build -t jaganegov/works-ui:develop-3eb63f6365-1 -f Dockerfile .
      
  login:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd frontend/micro-ui &&  docker push jaganegov/works-ui:develop-3eb63f6365-1
